name: MAGGuilds
version: 4.0.28
main: pl.maghub.guilds.MAGGuildsPlugin
api-version: '1.18'
author: MAGHUB
website: https://maghub.eu
softdepend: [PlaceholderAPI, MAGHUB-Core, MAGHUB-DROP]

commands:
  g:
    description: Glowna komenda gildii
    usage: /g
    aliases: [gildia, guild]
  ga:
    description: Administracja MAGGuilds
    usage: /ga

permissions:
  magguilds.admin:
    default: op
  magguilds.create:
    default: true
  magguilds.antylogout.bypass:
    default: false
  magguilds.regeneration.bypass-cost:
    default: op
